# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/scripting_entity/Desktop/projects/librariesLune/Gem/Gem-C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/scripting_entity/Desktop/projects/librariesLune/Gem/Gem-C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/scripting_entity/Desktop/projects/librariesLune/Gem/Gem-C/CMakeFiles /home/scripting_entity/Desktop/projects/librariesLune/Gem/Gem-C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/scripting_entity/Desktop/projects/librariesLune/Gem/Gem-C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gem

# Build rule for target.
gem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gem
.PHONY : gem

# fast build rule for target.
gem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/build
.PHONY : gem/fast

backend/compiler.o: backend/compiler.cpp.o
.PHONY : backend/compiler.o

# target to build an object file
backend/compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/compiler.cpp.o
.PHONY : backend/compiler.cpp.o

backend/compiler.i: backend/compiler.cpp.i
.PHONY : backend/compiler.i

# target to preprocess a source file
backend/compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/compiler.cpp.i
.PHONY : backend/compiler.cpp.i

backend/compiler.s: backend/compiler.cpp.s
.PHONY : backend/compiler.s

# target to generate assembly for a file
backend/compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/compiler.cpp.s
.PHONY : backend/compiler.cpp.s

backend/lexer.o: backend/lexer.cpp.o
.PHONY : backend/lexer.o

# target to build an object file
backend/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/lexer.cpp.o
.PHONY : backend/lexer.cpp.o

backend/lexer.i: backend/lexer.cpp.i
.PHONY : backend/lexer.i

# target to preprocess a source file
backend/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/lexer.cpp.i
.PHONY : backend/lexer.cpp.i

backend/lexer.s: backend/lexer.cpp.s
.PHONY : backend/lexer.s

# target to generate assembly for a file
backend/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/lexer.cpp.s
.PHONY : backend/lexer.cpp.s

backend/parser.o: backend/parser.cpp.o
.PHONY : backend/parser.o

# target to build an object file
backend/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/parser.cpp.o
.PHONY : backend/parser.cpp.o

backend/parser.i: backend/parser.cpp.i
.PHONY : backend/parser.i

# target to preprocess a source file
backend/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/parser.cpp.i
.PHONY : backend/parser.cpp.i

backend/parser.s: backend/parser.cpp.s
.PHONY : backend/parser.s

# target to generate assembly for a file
backend/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/backend/parser.cpp.s
.PHONY : backend/parser.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gem.dir/build.make CMakeFiles/gem.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gem"
	@echo "... backend/compiler.o"
	@echo "... backend/compiler.i"
	@echo "... backend/compiler.s"
	@echo "... backend/lexer.o"
	@echo "... backend/lexer.i"
	@echo "... backend/lexer.s"
	@echo "... backend/parser.o"
	@echo "... backend/parser.i"
	@echo "... backend/parser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

